[project]
name = "activitystat-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "colorlog>=6.9.0",
    "fastapi>=0.115.6",
    "pandas>=2.2.3",
    "uvicorn>=0.34.0",
]
